# Copyright (c) 2025 Akanksha Chaudhari, Matt Sinclair
# All rights reserved.
#
# This file contains modifications and/or code derived from:
# gem5-SALAM: https://github.com/TeCSAR-UNCC/gem5-SALAM
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
# contributors may be used to endorse or promote products derived from this
# software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

Import("*")

if env["CONF"]["USE_ARM_ISA"]:

    # Example
    # SimObject('IOAcc.py')

    # CommInterface
    SimObject("CommInterface.py", sim_objects=["CommInterface"])
    SimObject("ScratchpadMemory.py", sim_objects=["ScratchpadMemory"])
    SimObject("NoncoherentDma.py", sim_objects=["NoncoherentDma"])
    SimObject("StreamDma.py", sim_objects=["StreamDma"])
    SimObject("AccCluster.py", sim_objects=["AccCluster"])
    SimObject("StreamBuffer.py", sim_objects=["StreamBuffer"])
    SimObject("RegisterBank.py", sim_objects=["RegisterBank"])

    # LLVMInterface
    SimObject("AccComputeUnit.py", sim_objects=["AccComputeUnit"])
    SimObject("LLVMInterface.py", sim_objects=["LLVMInterface"])

    # HWInterface
    SimObject("CycleCounts.py", sim_objects=["CycleCounts"])
    SimObject(
        "FunctionalUnits.py",
        sim_objects=[
            "FunctionalUnits",
            "BitRegister",
            "DoubleMultiplier",
            "BitwiseOperations",
            "DoubleAdder",
            "FloatDivider",
            "BitShifter",
            "IntegerMultiplier",
            "IntegerAdder",
            "DoubleDivider",
            "FloatAdder",
            "FloatMultiplier",
        ],
    )
    SimObject("HWInterface.py", sim_objects=["HWInterface"])
    SimObject("HWStatistics.py", sim_objects=["HWStatistics"])
    SimObject(
        "InstConfig.py",
        sim_objects=[
            "InstConfig",
            "Add",
            "Addrspacecast",
            "Alloca",
            "AndInst",
            "Ashr",
            "Bitcast",
            "Br",
            "Call",
            "Fadd",
            "Fcmp",
            "Fdiv",
            "Fence",
            "Fmul",
            "Fmuladd",
            "Fneg",
            "Fpext",
            "Fptosi",
            "Fptoui",
            "Fptrunc",
            "Frem",
            "Fsub",
            "Gep",
            "Icmp",
            "Indirectbr",
            "Inttoptr",
            "Invoke",
            "Landingpad",
            "Load",
            "Lshr",
            "Mul",
            "OrInst",
            "Phi",
            "Ptrtoint",
            "Resume",
            "Ret",
            "Sdiv",
            "Select",
            "Sext",
            "Shl",
            "Srem",
            "Store",
            "Sub",
            "SwitchInst",
            "Trunc",
            "Udiv",
            "Uitofp",
            "Unreachable",
            "Urem",
            "Vaarg",
            "XorInst",
            "Zext",
        ],
    )
    SimObject("InstOpCodes.py", sim_objects=["InstOpCodes"])
    SimObject("SALAMPowerModel.py", sim_objects=["SALAMPowerModel"])
    SimObject("SimulatorConfig.py", sim_objects=["SimulatorConfig"])

    # Functional Units
    # SimObject('Adder.py')

    #
    Source("comm_interface.cc")
    Source("acc_compute_unit.cc")
    Source("llvm_interface.cc")
    Source("dma_write_fifo.cc")
    Source("noncoherent_dma.cc")
    Source("stream_dma.cc")
    Source("acc_cluster.cc")
    Source("stream_buffer.cc")
    Source("stream_port.cc")
    Source("scratchpad_memory.cc")
    Source("register_bank.cc")

    #
    Source("LLVMRead/src/value.cc")
    Source("LLVMRead/src/function.cc")
    Source("LLVMRead/src/basic_block.cc")
    Source("LLVMRead/src/debug_flags.cc")
    Source("LLVMRead/src/mem_request.cc")
    Source("LLVMRead/src/instruction.cc")
    Source("LLVMRead/src/registers.cc")
    Source("LLVMRead/src/operand.cc")

    Source("HWModeling/src/cycle_counts.cc")
    #Source('HWModeling/src/cacti_wrapper.cc')
    Source("HWModeling/src/functional_units.cc")
    Source("HWModeling/src/hw_interface.cc")
    Source("HWModeling/src/hw_statistics.cc")
    Source("HWModeling/src/instruction_config.cc")
    Source("HWModeling/src/opcodes.cc")
    Source("HWModeling/src/salam_power_model.cc")
    Source("HWModeling/src/simulator_config.cc")

    #
    DebugFlag("CommInterface")
    DebugFlag("CommInterfaceQueues")
    DebugFlag("DeviceMMR")
    DebugFlag("LLVMInterface")
    DebugFlag("NoncoherentDma")
    DebugFlag("LLVMParse")
    DebugFlag("Runtime")
    DebugFlag("RuntimeCompute")
    DebugFlag("RuntimeQueues")
    DebugFlag("SALAM_Debug")
    DebugFlag("StreamBuffer")
    DebugFlag("StreamDma")
    DebugFlag("Trace")
    DebugFlag("Step")

    #
    CompoundFlag(
        "JDEV",
        [
            "LLVMInterface",
            "CommInterface",
            "Runtime",
            "RuntimeCompute",
            "RuntimeQueues",
            "SALAM_Debug",
        ],
    )
    CompoundFlag("HWACC", ["CommInterface", "LLVMInterface"])
