---
acc_cluster:
  - Name: lenet5_clstr
  - DMA:
    - Name: dma
      BufferSize: 128
      MaxReqSize: 64
      PIOMaster: LocalBus
      Type: NonCoherent
      InterruptNum: 95
  - DMA:
    - Name: StreamDma
      PIOMaster: LocalBus
      Size: 8
      Type: Stream
      ReadInt: 210
      WriteInt: 211
      BufferSize: 128
  - Accelerator:
    - Name: top
      IrPath: hw/ir/top.ll
      PIOSize: 9
      PIOMaster: LocalBus
      LocalSlaves: LocalBus
      Debug: False
      InterruptNum: 68
  - Accelerator:
    - Name: data_mover_0
      IrPath: hw/ir/data_mover_0.ll
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
      StreamOut: StreamDma
    - Var:
      - Name: Conv0LineBuff
        Type: SPM
        Size: 640
        Ports: 25
  - Accelerator:
    - Name: conv0
      IrPath: hw/ir/conv0.ll
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
    - Var:
      - Name: Conv0Weights
        Type: SPM
        Size: 600
        Ports: 25
    - Var:
      - Name: Conv0Window
        Type: SPM
        Size: 100
        Ports: 25
        ReadyMode: True
        ResetOnRead: True
        WriteOnValid: False
        Connections: data_mover_0:25
    - Var:
      - Name: Conv0Out
        Type: Stream
        StreamSize: 4
        BufferSize: 16
        InCon: conv0
        OutCon: pool_mover_0
  - Accelerator:
    - Name: pool_mover_0
      IrPath: hw/ir/pool_mover_0.ll
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
  - Accelerator:
    - Name: pool0
      IrPath: hw/ir/pool0.ll
      Debug: True
      PIOSize: 1
      PIOMaster: LocalBus
    - Var:
      - Name: Pool0Window
        Type: SPM
        Size: 1344
        Ports: 4
        ReadyMode: True
        ResetOnRead: True
        WriteOnValid: False
        Connections: pool_mover_0:4
    - Var:
      - Name: Pool0Out
        Type: Stream
        StreamSize: 4
        BufferSize: 16
        InCon: pool0
        OutCon: data_mover_1
  - Accelerator:
    - Name: data_mover_1
      IrPath: hw/ir/data_mover_1.ll
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
    - Var:
      - Name: Conv1LineBuff
        Type: SPM
        Size: 4704
        Ports: 150
  - Accelerator:
    - Name: conv1
      IrPath: hw/ir/conv1.ll
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
    - Var:
      - Name: Conv1Weights
        Type: SPM
        Size: 9600
        Ports: 150
    - Var:
      - Name: Conv1Window
        Type: SPM
        Size: 600
        Ports: 150
        ReadyMode: True
        ResetOnRead: True
        WriteOnValid: False
        Connections: data_mover_1:150
    - Var:
      - Name: Conv1Out
        Type: Stream
        StreamSize: 4
        BufferSize: 16
        InCon: conv1
        OutCon: pool_mover_1
  - Accelerator:
    - Name: pool_mover_1
      IrPath: hw/ir/pool_mover_1.ll
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
  - Accelerator:
    - Name: pool1
      IrPath: hw/ir/pool1.ll
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
    - Var:
      - Name: Pool1Window
        Type: SPM
        Size: 1280
        Ports: 4
        ReadyMode: True
        ResetOnRead: True
        WriteOnValid: False
        Connections: pool_mover_1:4
    - Var:
      - Name: Pool1Out
        Type: Stream
        StreamSize: 4
        BufferSize: 16
        InCon: pool1
        OutCon: data_mover_2
  - Accelerator:
    - Name: data_mover_2
      IrPath: hw/ir/data_mover_2.ll
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
    - Var:
      - Name: Conv2LineBuff
        Type: SPM
        Size: 1600
        Ports: 400
  - Accelerator:
    - Name: conv2
      IrPath: hw/ir/conv2.ll
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
    - Var:
      - Name: Conv2Weights
        Type: SPM
        Size: 192000
        Ports: 400
    - Var:
      - Name: Conv2Window
        Type: SPM
        Size: 1600
        Ports: 400
        ReadyMode: True
        ResetOnRead: True
        WriteOnValid: False
        Connections: data_mover_2:400
    - Var:
      - Name: Conv2Out
        Type: Stream
        StreamSize: 4
        BufferSize: 16
        InCon: conv2
        OutCon: data_mover_3
  - Accelerator:
    - Name: data_mover_3
      IrPath: hw/ir/data_mover_3.ll
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
    - Var:
      - Name: FC0LineBuff
        Type: SPM
        Size: 480
        Ports: 120
  - Accelerator:
    - Name: fc0
      IrPath: hw/ir/fc0.ll
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
      StreamIn: StreamDma
    - Var:
      - Name: FC0Weights
        Type: SPM
        Size: 40320
        Ports: 120
    - Var:
      - Name: FC0Window
        Type: SPM
        Size: 480
        Ports: 120
        ReadyMode: True
        ResetOnRead: True
        WriteOnValid: False
        Connections: data_mover_3:12
hw_config:
  top:
  conv0:
  conv1:
  conv2:
  fc0:
  pool0:
  pool1:
  fc1:
  data_mover_0:
  data_mover_1:
  data_mover_2:
  data_mover_3:
  data_mover_4:
  pool_mover_0:
  pool_mover_1: