#!/usr/bin/env python3
"""Validate SALAM area stats, autogenerated HotSpot floorplan, and thermal traces."""

from __future__ import annotations

import argparse
import csv
import json
import sys
from collections import defaultdict
from pathlib import Path


def _read_stats(path: Path) -> list[dict]:
    entries: dict[str, dict] = {}
    stat_suffix = {
        "fuAreaUm2": "fu",
        "regAreaUm2": "reg",
        "spmAreaUm2": "spm",
        "areasReady": "ready",
    }
    for line in path.read_text().splitlines():
        if ".salam_power_model.power." not in line:
            continue
        parts = line.split()
        if len(parts) < 2:
            continue
        stat_name = parts[0].rsplit(".", 1)[-1]
        if stat_name not in stat_suffix:
            continue
        pm_path = parts[0].rsplit(".power.", 1)[0]
        entries.setdefault(pm_path, {})[stat_suffix[stat_name]] = float(
            parts[1]
        )
    return [{"path": path, **vals} for path, vals in sorted(entries.items())]


def _read_csv(path: Path):
    with path.open() as f:
        return list(csv.DictReader(f))


def _block_kind(label: str) -> str:
    return label.rsplit(".", 1)[-1]


def analyze_thermal_spread(rows, label_prefix: str) -> dict:
    """Check per-block temperature spread after HotSpot is active."""
    by_tick: dict[str, dict[str, float]] = defaultdict(dict)
    for row in rows:
        label = row.get("label", "")
        if label_prefix and label_prefix not in label:
            continue
        tick = row["tick"]
        by_tick[tick][label] = float(row["temp_k"])

    if not by_tick:
        return {"intervals": 0, "max_spread_k": 0.0, "heated_intervals": 0}

    spreads = []
    heated = 0
    for tick in sorted(by_tick, key=int):
        temps = list(by_tick[tick].values())
        if not temps:
            continue
        spread = max(temps) - min(temps)
        spreads.append(spread)
        if max(temps) > 300.0 + 1e-6:
            heated += 1

    return {
        "intervals": len(spreads),
        "max_spread_k": max(spreads) if spreads else 0.0,
        "heated_intervals": heated,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--m5out", type=Path, required=True)
    parser.add_argument(
        "--label-prefix",
        default="",
        help="Filter thermal rows to labels containing this prefix.",
    )
    parser.add_argument(
        "--expect-geometry",
        choices=("area", "fixed", "any"),
        default="area",
    )
    parser.add_argument(
        "--min-spm-width-m",
        type=float,
        default=0.001,
        help="Minimum expected SPM block width in area mode.",
    )
    parser.add_argument(
        "--min-heated-intervals",
        type=int,
        default=1,
        help="Minimum thermal intervals with temp > ambient.",
    )
    args = parser.parse_args()

    stats_path = args.m5out / "stats.txt"
    floorplan_path = args.m5out / "salam_hotspot_floorplan.json"
    thermal_path = args.m5out / "thermal_trace.csv"

    failed = False

    if not stats_path.is_file():
        print(f"FAIL: missing {stats_path}", file=sys.stderr)
        return 2

    area_entries = _read_stats(stats_path)
    if not area_entries:
        print("FAIL: no SALAM area stats found in stats.txt")
        failed = True
    else:
        for entry in area_entries:
            path = entry["path"]
            ready = entry.get("ready", 0.0)
            print(
                f"areas {path}: fu={entry.get('fu', 0):.1f} "
                f"reg={entry.get('reg', 0):.1f} "
                f"spm={entry.get('spm', 0):.1f} ready={ready:.0f}"
            )
            if ready < 1.0:
                print(f"FAIL: areasReady != 1 for {path}")
                failed = True
            if entry.get("spm", 0.0) <= entry.get("reg", 0.0):
                print(
                    f"WARN: spm area <= reg area for {path} "
                    "(expected spm >> reg for default 4096B SPM)"
                )

    if args.expect_geometry != "any" and not floorplan_path.is_file():
        print(f"FAIL: missing autogenerated floorplan log: {floorplan_path}")
        failed = True
    elif floorplan_path.is_file():
        floorplan = json.loads(floorplan_path.read_text())
        mode = floorplan.get("geometry_mode", "")
        passthrough = floorplan.get("passthrough_steps_before_build", 0)
        print(
            f"floorplan: mode={mode} passthrough_steps={passthrough} "
            f"blocks={len(floorplan.get('blocks', []))}"
        )
        if args.expect_geometry != "any" and mode != args.expect_geometry:
            print(
                f"FAIL: expected geometry {args.expect_geometry}, got {mode}"
            )
            failed = True

        blocks = {b["name"]: b for b in floorplan.get("blocks", [])}
        for name, block in sorted(blocks.items()):
            kind = _block_kind(name)
            print(
                f"  {name}: {block['width_m']*1e3:.3f}x{block['height_m']*1e3:.3f} mm "
                f"area_um2={floorplan.get('block_areas_um2', {}).get(name, 0):.1f}"
            )
            if kind == "spm" and mode == "area":
                if block["width_m"] < args.min_spm_width_m:
                    print(
                        f"FAIL: SPM block {name} width {block['width_m']} "
                        f"< {args.min_spm_width_m}"
                    )
                    failed = True

    if thermal_path.is_file():
        thermal_rows = _read_csv(thermal_path)
        spread = analyze_thermal_spread(thermal_rows, args.label_prefix)
        print(
            f"thermal: intervals={spread['intervals']} "
            f"heated={spread['heated_intervals']} "
            f"max_spread={spread['max_spread_k']:.6f} K"
        )
        if spread["heated_intervals"] < args.min_heated_intervals:
            print(
                f"FAIL: only {spread['heated_intervals']} heated intervals "
                f"(expected >= {args.min_heated_intervals})"
            )
            failed = True
        if spread["max_spread_k"] <= 0.0 and spread["heated_intervals"] > 0:
            print("FAIL: blocks heated but no inter-block temperature spread")
            failed = True
    else:
        print(f"WARN: no thermal trace at {thermal_path}")

    if failed:
        print("FAIL: floorplan / area validation failed")
        return 1

    print("OK: floorplan, area stats, and thermal traces look consistent")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
